### ISSUE TITLE
Icon button shouldn't activate on unhandled context-click

### ISSUE THREAD

**Issue by dmazzoni-google** [PolymerElements/paper-icon-button#5] opened 2015-05-08 17:00 UTC
Right-clicking on an icon button shouldn't show its activation animation. Maybe if it specifically has a long-press handler, it could - but not if it just shows the default browser context menu.

**Comment by notwaldorf** [comment] 2015-06-18 19:30
(@cdata: there may already be a bug open for this already. looking)

**Comment by notwaldorf** [comment] 2015-06-19 17:54
Clising as a duplicate of https://github.com/PolymerElements/paper-radio-button/issues/33
(they have the same root case)

**Closed by notwaldorf** 2015-06-19 17:54 UTC
Labels: bug, duplicate
