### ISSUE TITLE
[1.0] 'tabindex' is not restored after toggling 'disabled'

### ISSUE THREAD

**Issue by dzhioev** [PolymerElements/paper-icon-button#20] opened 2015-06-05 05:46 UTC
Steps to reproduce:
1. Create `<paper-icon-button>`
2. Disable it.
3. Enable it.
The button has 'tabindex' equal to -1 after that, as a result it is not focusable by Tab.
Browser: Google Chrome Version 43.0.2357.73 beta (64-bit)
Demo: http://dzhioev.net:8080/paper_icon_tabindex.html

**Comment by notwaldorf** [comment] 2015-06-10 19:16
This has the same root cause as https://github.com/PolymerElements/paper-icon-button/issues/19 -- the duplicate behaviour is calling the `disabledChanged` observer twice, which resets the `_oldTabIndex` twice (and the second time to -1, thus killing any hope of restoring it to a good value in the future).

**Comment by notwaldorf** [comment] 2015-06-16 19:28
Fixed with https://github.com/PolymerElements/paper-icon-button/pull/18

**Closed by notwaldorf** 2015-06-16 19:28 UTC
