### ISSUE TITLE
Paper-icon-button stays in tapped state once tapped in ios9

### ISSUE THREAD

**Issue by mbergeron** [PolymerElements/paper-icon-button#49] opened 2015-10-03 03:49 UTC
Paper-icon-button stays in tapped state once tapped in ios9.

Picture comes from the Polymer demo page

![image](https://cloud.githubusercontent.com/assets/1834714/10261320/1c43c9d0-6960-11e5-8748-be3dd867e3c4.png)

**Comment by kbwatts** [comment] 2015-12-10 20:13
+1

(Can also use `toggles` attribute to make it appear intentional, if that doesn't screw up your ux.)

**Comment by notwaldorf** [comment] 2015-12-10 23:22
It doesn't stay toggled, that's the visual focus state (since the button is focused after clicking, and stays focused). On a desktop, if you tab to a button you'll see the same thing.

O mobile, I've noticed this happens for native `a` links as well: http://jsbin.com/gupica/edit?html,output, so I'm not sure it's a bug

**Comment by kbwatts** [comment] 2015-12-11 05:06
You're right that the cause of this 'bug' is the `:focus` state which is not itself a problem. However, what does still seem like a bug is that the ripple disappears and THEN the focus state appears, making it look like it gets 'toggled' after the user taps it.

See this video recording using latest iOS - the paper-icon-button gets tapped only 2 times in this video, but the on state appears to get triggered 4 times because of this combined effect of ripple + `:focus` - https://youtu.be/UQq_OJjZxjM

**Comment by cdata** [comment] 2016-02-03 21:45
Hi, I'm going to close this issue as a dupe of https://github.com/PolymerElements/paper-button/issues/24, since it is the same problem. Please refer to the `paper-button` issue for future discussion and tracking!

**Closed by cdata** 2016-02-03 21:45 UTC
