### ISSUE TITLE
paper-icon-button drawn in the pressed state after browser tab switching bug

### ISSUE THREAD

**Issue by vadimgo** [PolymerElements/paper-icon-button#27] opened 2015-06-23 17:20 UTC
Click on the paper-icon-button on the page below, then switch away to a different tab, then switch back -  as a result the button is drawn in the pressed state, i.e. as if it's in the process of being pressed.  Simple repro with the following page:

<html>
<head>
  <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="bower_components/iron-icons/av-icons.html">
  <link rel="import" href="bower_components/paper-icon-button/paper-icon-button.html">
</head>
<body unresolved>
  <paper-icon-button icon="av:play-arrow"></paper-icon-button>
</body>
</html>

**Comment by vadimgo** [comment] 2015-06-23 17:23
This also reproduces with

https://elements.polymer-project.org/bower_components/paper-icon-button/demo/index.html

Just click on one of the buttons.
Switch away to a different tab, then switch back.

The button previously clicked is drawn in the "pressed" state.

**Comment by notwaldorf** [comment] 2015-06-23 17:35
Duplicate of https://github.com/PolymerElements/paper-radio-button/issues/33

**Closed by notwaldorf** 2015-06-23 17:35 UTC
Labels: duplicate
