### ISSUE TITLE
[Firefox] - It needs to be tapped twice to work

### ISSUE THREAD

**Issue by manfield** [PolymerElements/paper-icon-button#51] opened 2015-10-12 14:14 UTC
On Firefox we encountered that paper-icon-button does not behave correctly on "on-tap" event.
It needs to be tapped twice to fire event.

**Comment by notwaldorf** [comment] 2015-10-12 19:43
Duplicate of https://github.com/PolymerElements/paper-behaviors/issues/34

**Closed by notwaldorf** 2015-10-12 19:43 UTC

**Comment by manfield** [comment] 2015-10-12 21:23
Alright! thanks
